name: MineCordBot
version: 2.1.0
author: CyRien
description: Discord bot that bridge chat from minecraft to discord

main: us.cyrien.minecordbot.main.Minecordbot

permissions:
    minecordbot.reload:
        description: Allow to reload MineCordBot config.
        default: op
    minecordbot.incognito:
        description: Hide player from all broadcast to discord.
        default: false
    minecordbot.dme:
        description: Allow user to express themselves to discord and minecraft.
        default: op