Configuration:
######################################
############ BOT SETTINGS ############
######################################
  Bot:
    # Bot token can be found on your Discord application page.
    Bot_Token: sample.botToken
    # Bot ID, this is also known as Client ID on your Discord application page.
    Bot_ID: 1234567890123
    # Owner ID of the owner of the bot, server, or guild.
    Owner_ID: 1234012038201
    # Set of character that distinguish if it's a command.
    Command_Trigger: !!
    # Should bot's command responses be deleted after 5 minutes?
    Delete_Response: false
    # What language should the bot respond with.
    # Available localizations:
    # en, en_s7(pirate), es, fr, pl, ro, de
    Localization: en
    # This will be the game of the bot and will be shown under the name
    # of the bot as "Playing <Default_Game>"
    Default_Game: default
######################################
########### CHAT SETTINGS ############
######################################
  Chat:
    # Channel ID's of text channels you want to bind Minecraft chat with
    Relay_Channels:
      - 1312312312312312313
      - 1312312312312312312
      - 1231231231321231231
    # Prefix of messages that came from Discord. This can be formatted.
    # Place holders:
    # {sender}, {guild}, {name}, {ename}, {role}, {channel}
    Discord_Prefix: &6&l[Discord] &r{role} {ename}:
    # Prefix of messages that came from Discord.
    # Place holders:
    # {world}, {ename}, {erank}, {rank_group}, {rank_prefix}
    # {sender}, {name}.
    Minecraft_Prefix: [Minecraft] {erank} {ename}:
    # If a message from Discord is a command with any of the prefix
    # below. That message won't be relayed to Minecraft.
    Blocked_Prefix: [~, ~~]
    # If a message from Discord came from any of the Bots below.
    # That message won't be relayed to Minecraft.
    Blocked_Bots:
      - 123456788900099
      - 312312312312312
######################################
####### MOD CHANNEL SETTINGS #########
######################################
  Mod_Channel:
    # ID of the text channel you want to make as a mod channel
    Mod_TextChannel: 123123123123123
    # Do you want to prevent messages that are being sent on the mod channel
    # to be relayed to Minecraft?
    One_Way: false
    # Do you want to see in-game chat on a mod channel?
    See_Chat: true
    # Do you want to see commands that are being executed on a mod channel?
    See_Commands: true
    # Do you want to see fake join/leave messages from SuperVanish on a mod channel?
    # Will be marked "(Vanish)"
    See_SV: true
    # Do you want to see broadcasts on a mod channel?
    See_Broadcast: true
######################################
######### BROADCAST SETTINGS #########
######################################
  Broadcast:
    # Will broadcast from other plugins be relayed to Discord?
    See_Plugin_Broadcast: true
    # Will player join event broadcast be relayed to Discord?
    See_Player_Join: true
    # Will player quit event broadcast be relayed to Discord?
    See_Player_Quit: true
    # Will player death event broadcast be relayed to Discord?
    See_Player_Death: true
    # Do players with minecordbot.incognito permission be hidden from
    # Join/Quit broadcast that are being relayed to Discord.
    Hide_Incognito_Player: true