name: MineCordBot
version: 2.1.0
author: CyRien
description: A powerful way to bridge Minecraft and Discord

main: us.cyrien.minecordbot.Minecordbot

permissions:
    minecordbot.reload:
        description: Allow to reload MineCordBot config.
        default: op
    minecordbot.incognito:
        description: Hide player from all broadcast to discord.
        default: false
    minecordbot.dme:
        description: Allow user to express themselves to discord and minecraft.
        default: op
    minecordbot.discordsync:
        description: Allow user to sync their Discord account to their Minecraft account.
        default: op